name: Cygwin 5.2

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/common.yml
    with:
      runs_on: windows-latest
      compiler: ocaml.5.2.0
      cygwin: true
      compiler_git_ref: refs/heads/5.2
      timeout: 360
