name: Cygwin 5.1

on:
  schedule:
    # Every Sunday morning, at 2:22 UTC
    - cron: '22 2 * * 0'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/common.yml
    with:
      runs_on: windows-latest
      compiler: ocaml-variants.5.1.1+options+win
      cygwin: true
      timeout: 240
