name: Cygwin 5.2

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/common.yml
    with:
      runs_on: windows-latest
      compiler: ocaml-variants.5.2.0~beta1+options+win
      cygwin: true
      timeout: 240
