name: Bytecode 5.0.0

on:
  schedule:
    # Every Sunday morning, at 1:11 UTC
    - cron: '11 1 * * 0'

jobs:
  build:
    uses: ./.github/workflows/common.yml
    with:
      compiler: 'ocaml-variants.5.0.0+options,ocaml-option-bytecode-only'
      timeout: 360
