name: 32bit 5.1

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: ./.github/workflows/common.yml
    with:
      compiler: 'ocaml-variants.5.1.1~rc1+options,ocaml-option-32bit'
      timeout: 240
