name: macOS-intel 5.2

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/common.yml
    with:
      compiler: 'ocaml-base-compiler.5.2.0~beta2'
      runs_on: 'macos-13'
