name: macOS 5.1

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: ./.github/workflows/common.yml
    with:
      compiler: 'ocaml-base-compiler.5.1.0~alpha2'
      runs_on: 'macos-latest'
