name: MSVC bytecode 5.3

on:
  schedule:
    # Every Monday morning, at 1:11 UTC
    - cron: '11 1 * * 1'
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/msvc-common.yml
    with:
      bytecodeonly: true
      compiler_ref: '5.3'
