name: Windows 5.1

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: ./.github/workflows/common.yml
    with:
      runs_on: windows-latest
      compiler: ocaml-variants.5.1.0+options+win,ocaml-option-mingw
      timeout: 240
