name: Windows 5.0.0

on:
  schedule:
    # Every Sunday morning, at 1:11 UTC
    - cron: '11 1 * * 0'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/common.yml
    with:
      runs_on: windows-latest
      compiler: ocaml.5.0.0,ocaml-option-mingw
      timeout: 360
